language: rust
cache: cargo
dist: trusty
os: 
  - linux
  - osx
  - windows
# Run builds for all the supported trains
rust:
  - nightly
  - stable
# The main build
script:
  - cargo build
  - RUST_BACKTRACE=full cargo test
